### ISSUE TITLE
Deleting post/board should also delete its media

### ISSUE THREAD

**Issue by zooool** [neeshy/picochan#1]
When you delete a post, whether it be an OP (thread) or a reply, its media should also automatically be deleted completely from the server unless it's not linked to any posts elsewhere on the site.

It's annoying to have to delete files first, then the post.

**Comment by zooool** [comment]
Like for deleting an entire board. All of the media posted on that board should be deleted from the server unless some of it is also posted/linked on another board.

**Comment by neeshy** [comment]
This has been fixed in 1b4b277c4dc151b8ec7e5317e49189f74c807b25. Thank you for opening this issue.
